
package com.tcs.bancs.services.provider.payments.transfers.implementations;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.tcs.bancs.morganstanley.payments.transfers.TransferResponse;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_02-b08-fcs
 * Generated source version: 2.0
 * 
 */
@WebService(name = "TransferRequest", targetNamespace = "http://tcs.com/bancs/morganstanley/payments/transfers")
public interface TransferRequest {


    /**
     * 
     * @param loadTransferRequestParam
     * @return
     *     returns com.tcs.bancs.morganstanley.payments.transfers.TransferResponse
     * @throws TransferRequestException
     */
    @WebMethod(action = "http://tcs.com/bancs/morganstanley/payments/transfers/loadTransfer")
    @WebResult(name = "LoadTransferResponseParam", targetNamespace = "http://tcs.com/bancs/morganstanley/payments/transfers/loadTransfer/response")
    @RequestWrapper(localName = "loadTransfer", targetNamespace = "http://tcs.com/bancs/morganstanley/payments/transfers", className = "com.tcs.bancs.morganstanley.payments.transfers.LoadTransfer")
    @ResponseWrapper(localName = "loadTransferResponse", targetNamespace = "http://tcs.com/bancs/morganstanley/payments/transfers", className = "com.tcs.bancs.morganstanley.payments.transfers.LoadTransferResponse")
    public TransferResponse loadTransfer(
        @WebParam(name = "loadTransferRequestParam", targetNamespace = "http://tcs.com/bancs/morganstanley/payments/transfers/loadTransfer/request")
        com.tcs.bancs.morganstanley.payments.transfers.TransferRequest loadTransferRequestParam)
        throws TransferRequestException
    ;

    /**
     * 
     * @param selectAccountRequestParam
     * @return
     *     returns com.tcs.bancs.morganstanley.payments.transfers.TransferResponse
     * @throws TransferRequestException
     */
    @WebMethod(action = "http://tcs.com/bancs/morganstanley/payments/transfers/selectAccount")
    @WebResult(name = "SelectAccountResponseParam", targetNamespace = "http://tcs.com/bancs/morganstanley/payments/transfers/selectAccount/response")
    @RequestWrapper(localName = "selectAccount", targetNamespace = "http://tcs.com/bancs/morganstanley/payments/transfers", className = "com.tcs.bancs.morganstanley.payments.transfers.SelectAccount")
    @ResponseWrapper(localName = "selectAccountResponse", targetNamespace = "http://tcs.com/bancs/morganstanley/payments/transfers", className = "com.tcs.bancs.morganstanley.payments.transfers.SelectAccountResponse")
    public TransferResponse selectAccount(
        @WebParam(name = "SelectAccountRequestParam", targetNamespace = "http://tcs.com/bancs/morganstanley/payments/transfers/selectAccount/request")
        com.tcs.bancs.morganstanley.payments.transfers.TransferRequest selectAccountRequestParam)
        throws TransferRequestException
    ;

    /**
     * 
     * @param createTransferRequestParam
     * @return
     *     returns com.tcs.bancs.morganstanley.payments.transfers.TransferResponse
     * @throws TransferRequestException
     */
    @WebMethod(action = "http://tcs.com/bancs/morganstanley/payments/transfers/createTransfer")
    @WebResult(name = "CreateTransferResponseParam", targetNamespace = "http://tcs.com/bancs/morganstanley/payments/transfers/createTransfer/response")
    @RequestWrapper(localName = "createTransfer", targetNamespace = "http://tcs.com/bancs/morganstanley/payments/transfers", className = "com.tcs.bancs.morganstanley.payments.transfers.CreateTransfer")
    @ResponseWrapper(localName = "createTransferResponse", targetNamespace = "http://tcs.com/bancs/morganstanley/payments/transfers", className = "com.tcs.bancs.morganstanley.payments.transfers.CreateTransferResponse")
    public TransferResponse createTransfer(
        @WebParam(name = "CreateTransferRequestParam", targetNamespace = "http://tcs.com/bancs/morganstanley/payments/transfers/createTransfer/request")
        com.tcs.bancs.morganstanley.payments.transfers.TransferRequest createTransferRequestParam)
        throws TransferRequestException
    ;

}
