
package com.tcs.bancs.services.provider.payments.transfers.implementations;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_02-b08-fcs
 * Generated source version: 2.0
 * 
 */
@WebFault(name = "TransferRequestException", targetNamespace = "http://tcs.com/bancs/morganstanley/payments/transfers")
public class TransferRequestException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private com.tcs.bancs.morganstanley.payments.transfers.TransferRequestException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public TransferRequestException(String message, com.tcs.bancs.morganstanley.payments.transfers.TransferRequestException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public TransferRequestException(String message, com.tcs.bancs.morganstanley.payments.transfers.TransferRequestException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.tcs.bancs.morganstanley.payments.transfers.TransferRequestException
     */
    public com.tcs.bancs.morganstanley.payments.transfers.TransferRequestException getFaultInfo() {
        return faultInfo;
    }

}
