
package com.tcs.bancs.services.provider.payments.transfers.implementations;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_02-b08-fcs
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "TransferRequestService", targetNamespace = "http://implementations.transfers.payments.provider.services.bancs.tcs.com/", wsdlLocation = "http://172.19.98.148:9085/BancsWSMobile/BancsWSProvider?wsdl")
public class TransferRequestService
    extends Service
{

    private final static URL TRANSFERREQUESTSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://172.19.98.148:9085/BancsWSMobile/BancsWSProvider?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        TRANSFERREQUESTSERVICE_WSDL_LOCATION = url;
    }

    public TransferRequestService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TransferRequestService() {
        super(TRANSFERREQUESTSERVICE_WSDL_LOCATION, new QName("http://implementations.transfers.payments.provider.services.bancs.tcs.com/", "TransferRequestService"));
    }

    /**
     * 
     * @return
     *     returns TransferRequest
     */
    @WebEndpoint(name = "TransferRequestPort")
    public TransferRequest getTransferRequestPort() {
        return (TransferRequest)super.getPort(new QName("http://implementations.transfers.payments.provider.services.bancs.tcs.com/", "TransferRequestPort"), TransferRequest.class);
    }

}
