name := """dependent-app"""

version := "1.0-SNAPSHOT"

lazy val root = (project in file(".")).enablePlugins(PlayJava)

scalaVersion := "2.11.1"

libraryDependencies ++= Seq(
  javaJdbc,
  cache,
  javaWs,
  filters,
  springContext,
  springCore,
  springExpression,
  springBean,
  springAop,
  springContextSupport,
  springTX,
  springJdbc,
  springORM,
  springOXM,
  springWeb, 
  springWebMVC,
  springWebMVCPortlet,
  springTest, 
  springBOM,
  springSecurity,
  hibernateCore, 
  hibernateValidator, 
  hibernateEntityManager,
  hibernatePersistance,
  hibernateAnnotations,
  hibernateCommonsAnnotations,
  expressionLanguage,
  deadboltCore,
  deadboltJava,
  gson,
  hikariCP,
  bouncycastle,
  jasypt,
  jasyptSpring, 
  slf4j,
  logbackClassic,
  logbackCore,
  easymock,
  quartz,
  jacksonCore,
  jacksonAnnotations, 
  jacksonDatabind,
  log4j,
  cglib,
  commonsCollection,
  commonsLang,
  commonsConfiguration,
  asm,
  aopAlliance,
  antlr,
  javassist,
  dom4J,
  json, 
  objenesis 
)
