package com.tcs.ebw.ejb.ejbclasses;


/*
  ** This file was automatically generated by 
  ** EJBGen WebLogic Server 9.2 SP0  Fri Jun 23 20:47:26 EDT 2006 783464 
*/


import javax.ejb.CreateException;
import javax.ejb.EJBHome;
import java.rmi.RemoteException;

//import weblogic.ejbgen.*;
// END imports from bean class


/**
 * * 
 * <code>GenericSessionBean</code> subclass automatically generated by Workshop.
 * Please flush out the {@link #ejbCreate()} method, add all desired business methods
 * and review the Session, JndiName and FileGeneration annotations to ensure the settings match
 * your intended use.
 
 */

public interface ChannelsEJBBeanRemoteHome extends EJBHome {




  /**
   * * 
 * ejbCreate
 
   */
  public ChannelsEJBBeanRemote create()     throws CreateException, RemoteException;



}
